version: '3.8'

services:
  
  db:
    container_name: db
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    networks:
      - my-app-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DatabaseConnection=Host=db; Port=5432; Database=ecommerce_db; Username=postgres; Password=postgres
    ports:
      - "5501:80"
    networks:
      - my-app-network
    depends_on: 
      - db

networks:
  my-app-network:
    driver: bridge